[package]
name = "bwa-sys"
version = "0.0.1"
authors = ["csyourui@gmail.com"]
license = "bwa/COPYING"
build = "build.rs"
links = "bwa"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.65.1"
cc = { version = "1.0", features = ["parallel"] }
